draw_self()
if (active == 1)
{
    if (global.bonus1 == 1)
    {
        if (!instance_exists(o_glitch_out))
            instance_create_depth(0, 0, -100, o_glitch_out)
        draw_set_color(c_white)
        draw_set_font(fnt_1)
        draw_text((x - 70), (o_player.y + 100), "An Error Has Occured.")
        draw_text((x - 70), (o_player.y + 130), "Please Restart the Game.")
        draw_text((x - 70), (o_player.y + 250), "He drowned that day.")
        draw_text((x - 70), (o_player.y + 280), "")
        draw_text((x - 70), (o_player.y + 300), "At the bottom of the lake")
        draw_text((x - 70), (o_player.y + 350), "She didn't save him")
        draw_text((x - 70), (o_player.y + 400), "It's not her fault.")
        draw_text((x - 70), (o_player.y + 450), "It's not her fault.")
    }
    if (global.bonus3 == 1)
    {
        if (!instance_exists(o_glitch_out))
            instance_create_depth(0, 0, -100, o_glitch_out)
        draw_set_color(c_white)
        draw_set_font(fnt_1)
        draw_text((x - 70), (o_player.y + 100), "An Error Has Occured.")
        draw_text((x - 70), (o_player.y + 130), "Please Restart the Game.")
        draw_text((x - 70), (o_player.y + 250), "The time was supposed")
        draw_text((x - 70), (o_player.y + 280), "")
        draw_text((x - 70), (o_player.y + 300), "To be happy.")
        draw_text((x - 70), (o_player.y + 350), "But she could feel her")
        draw_text((x - 70), (o_player.y + 400), "skin peeling off")
        draw_text((x - 70), (o_player.y + 450), "")
    }
    if (global.bonus2 == 1)
    {
        if (!instance_exists(o_glitch_out))
            instance_create_depth(0, 0, -100, o_glitch_out)
        draw_set_color(c_white)
        draw_set_font(fnt_1)
        draw_text((x - 70), (o_player.y + 100), "An Error Has Occured.")
        draw_text((x - 70), (o_player.y + 130), "Please Restart the Game.")
        draw_text((x - 70), (o_player.y + 250), "She's not gone.")
        draw_text((x - 70), (o_player.y + 280), "")
        draw_text((x - 70), (o_player.y + 300), "She's still here")
        draw_text((x - 70), (o_player.y + 350), "She wants you to free us.")
        draw_text((x - 70), (o_player.y + 400), "Please Free Us")
        draw_text((x - 70), (o_player.y + 450), "Please Free Us")
    }
}
