draw_self()
if (room == rm_claw_game)
{
    draw_set_font(fnt_1)
    draw_set_color(c_yellow)
    draw_text((room_width / 2.5), 250, "CLAW MACHINE GAME")
    draw_set_color(c_white)
    draw_text((room_width / 3), 400, "Press [Arrow Keys] to move around.")
    draw_text((room_width / 3), 450, "Press [Spacebar] to go grab.")
    draw_text((room_width / 3), 500, "You have 3 tries!")
    draw_set_color(c_gray)
    draw_text((room_width / 3), 600, "Press [Spacebar] to start!")
}
if (room == rm_lake_game)
{
    draw_set_font(fnt_1)
    draw_set_color(c_yellow)
    draw_text((room_width / 2.5), 250, "FISHING GAME")
    draw_set_color(c_white)
    draw_text((room_width / 3), 400, "Press [Spacebar] to go down.")
    draw_text((room_width / 3), 450, "Press [Left] and [Right] to Move.")
    draw_text((room_width / 3), 500, "CATCH 3 FISH TO WIN!")
    draw_set_color(c_gray)
    draw_text((room_width / 3), 600, "Press [Spacebar] to start!")
}
if (room == rm_music_game)
{
    draw_set_font(fnt_1)
    draw_set_color(c_yellow)
    draw_text((room_width / 2.5), 250, "MUSIC GAME")
    draw_set_color(c_white)
    draw_text((room_width / 3), 400, "Press [Arrow Keys] to play notes.")
    draw_text((room_width / 3), 450, "Miss a note and you lose.")
    draw_text((room_width / 3), 500, "PLAY THE SONG TO WIN!")
    draw_set_color(c_gray)
    draw_text((room_width / 3), 600, "Press [Spacebar] to start!")
}
if (room == rm_farm_game && (!instance_exists(o_margret_glitch)))
{
    draw_set_font(fnt_1)
    draw_set_color(c_yellow)
    draw_text((room_width / 2.5), 250, "SORTING GAME")
    draw_set_color(c_white)
    draw_text((room_width / 3), 400, "Press [Arrow Keys] to move your hand.")
    draw_text((room_width / 3), 450, "Press [Spacebar] to grab fruit.")
    draw_text((room_width / 3), 500, "SORT ALL THE FRUIT TO WIN!")
    draw_set_color(c_gray)
    draw_text((room_width / 3), 600, "Press [Spacebar] to start!")
}
if (room == rm_claus_game)
{
    draw_set_font(fnt_1)
    draw_set_color(c_yellow)
    draw_text((room_width / 2.5), 250, "I SPY GAME")
    draw_set_color(c_white)
    draw_text((room_width / 3), 400, "Press [Arrow Keys] to move your hand.")
    draw_text((room_width / 3), 450, "Press [Spacebar] to select the right object.")
    draw_text((room_width / 3), 500, "FOLLOW THE INSTUCTIONS TO WIN!")
    draw_set_color(c_gray)
    draw_text((room_width / 3), 600, "Press [Spacebar] to start!")
    draw_text((room_width / 3), 1050, "Uijt jt bmm zpvs gbvmu.")
}
if (room == rm_barn_1)
{
    draw_set_font(fnt_1)
    draw_set_color(c_yellow)
    draw_text(768, 2650, "MAZE GAME")
    draw_set_color(c_white)
    draw_text(640, 2842, "Press [Arrow Keys] to move around.")
    draw_text(640, 2892, "avoid the eyes")
    draw_text(640, 2942, "GET TO THE 4TH AREA WIN!")
    draw_set_color(c_gray)
    draw_text(640, 3042, "Press [Spacebar] to start!")
}
if (room == rm_maze_1)
{
    draw_set_font(fnt_1)
    draw_set_color(c_yellow)
    draw_text(768, 2650, "TAG GAME")
    draw_set_color(c_white)
    draw_text(640, 2842, "Press [Arrow Keys] to move around.")
    draw_text(640, 2892, "Press [Spacebar] to collect pumpkins.")
    draw_text(640, 2942, "GET ALL PUMPKINS TO WIN!")
    draw_text(640, 3002, "                                         don't get caught.")
    draw_set_color(c_gray)
    draw_text(640, 3042, "Press [Spacebar] to start!")
}
if (room == rm_maze_2)
{
    draw_set_font(fnt_1)
    draw_set_color(c_yellow)
    draw_text(768, 2650, "TAG GAME")
    draw_set_color(c_white)
    draw_text(640, 2842, "Press [Arrow Keys] to move around.")
    draw_text(640, 2892, "")
    draw_text(640, 2942, "CATCH PETER THE PUMPKIN TO WIN!")
    draw_text(640, 3002, "")
    draw_set_color(c_gray)
    draw_text(640, 3042, "Press [Spacebar] to start!")
}
